### ISSUE TITLE
Create a map to play on

### ISSUE THREAD

**Issue by Jarichio** [TechnoShip123/MonkeBusiness#13]
The actual map, that the player is going to play on. Y'know 'cause that's also important, stupid players
### Subtasks
- [ ] #14
- [ ] #15
- [ ] #16

**Comment by TechnoShip123** [comment]
### Subtasks
- [ ] Create rough map layout
- [ ] Add textures for map
- [ ] Add extra details & improvements to map
